"""
The application data model represented by objects including:
- SQLAlchemy declarative mappers
- Pydantic models
- Enums
- Modeling constants

Packaged by topic.

Each domain object has at least an SQLAlchemy mapper and a Pydantic model, which is serves
as the API representation.

E.g.:

```py
class ThingModel(Model):
    # ...

class Thing(Mapper):
    __model__ = ThingModel
    __tablename__ = "things"

    id: Mapped[UUID] = pk_column()
    # ...
```

Most queries are implemented as class methods of SQLAlchemy mappers.

*Note*: App type definitions are generated by indexing this module, meaning all data
model constructs of which the app should be aware must be imported to here.
"""
import inspect

from .base import Mapper, Model, EnumMixin
from .common import current_datetime, get_fernet_encryption
from .audit import (
    AuditSummaryModel, Audit, AuditModel, AuditMixin, BasicAuditEvent,
    AuditStandaloneModel
)
from .user import (
    User, UserModel, AuthKey, AuthKeyModel, Role, Permission, UserRole,
    UserRoleModel, AuthKeyRestriction, ROLE_SCOPES, PERMISSIONS_MATRIX,
    MAX_USER_NAME_LENGTH, MAX_USER_EMAIL_LENGTH
)
from .realm import Realm, RealmModel, RealmType
from .upload import Upload, UploadModel, UploadType
from .notification import (
    Notification, NotificationModel, NotificationType, NotificationEmailStatus
)

# Handle circular refs in Pydantic models.
_rebuild: list[type[Model]] = [
    AuditModel, UploadModel, UserModel, AuditSummaryModel, UserGrantModel,
    AuditStandaloneModel, RealmModel
]
for model_cls in _rebuild:
    model_cls.model_rebuild()

def mappers() -> list[type[Mapper]]:
    """
    Return all SQLAlchemy mapper types.
    """
    return [
        symbol for symbol in globals().values() if (
            inspect.isclass(symbol) and
            issubclass(symbol, Mapper) and
            symbol is not Mapper
        )
    ]

def mapper_for_tablename(tablename: str) -> type[Mapper]:
    """
    Return the SQLAlchemy mapper type for the given `tablename`.
    """
    for symbol in mappers():
        if getattr(symbol, "__tablename__", None) == tablename:
            return symbol

    raise ValueError(tablename)
