include /etc/nginx/mime.types;
include /etc/nginx/mime.types.extra;

error_log /dev/stderr info;
access_log /dev/stdout;

server {
    listen __SERVICE_PORT;
    listen [::]:__SERVICE_PORT;
    server_name __SERVER_NAME;

    location / {
        root /app/dist;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /health {
        add_header Content-Type text/plain;
        return 200 'healthy';
    }
}
