"""
Base API service implementation.

*Note*: App types are generated by indexing this module, so all request and response
`Model`s defined in this package must be imported to here.
"""
# Imports for codegen.
from backend.service import AuthWSParams
from backend.channels import (
    GoogleDV360OAuthMetadataModel, GoogleDV360ChannelSettingsModel,
    GoogleDV360ChannelSettingsOptionsModel, GoogleDV360AudienceModel,
    GoogleDV360AccountModel, GoogleDV360TargetingMethod, MetaOAuthMetadataModel,
    MetaOAuthIdentityModel, MetaOAuthBusinessModel, MetaChannelSettingsModel,
    MetaChannelSettingsOptionsModel, MetaConversionEventType, SnapchatOAuthMetadataModel,
    SnapchatOAuthIdentityModel, SnapchatOAuthOrgModel, TikTokIdentityModel,
    TikTokOAuthMetadataModel, AmazonOAuthMetadataModel, AmazonManagerAccountModel,
    AmazonDSPAdvertiserModel, AmazonDSPProfileModel, AmazonProductCategoryModel,
    AmazonProductSubCategoryModel, AmazonChannelSettingsModel,
    AmazonChannelSettingsOptionsModel, PinterestOAuthMetadataModel,
    PinterestAdAccountModel, GoogleAdsOAuthMetadataModel,
    GoogleAdsOAuthAccountTierModel, GoogleAdsOAuthManageTierModel,
    GoogleAdsSearchKeyword, GoogleAdsSearchKeywordMatchType,
    GoogleAdsChannelSettingsModel
)
from backend.analytics import (
    AnalyticsModel, DailyMetricsModel, RawAnalyticsModel, PerformanceMetricsModel,
    RawAnalyticsTrendModel
)
from backend.ai import (
    ImageGenOptionsModel, ImageGenSizeOption, ImageGenAspectRatioOption,
    ImageGenMimeTypeOption
)
from backend.logic import BoundingBoxModel

from .common import StateUpdateParams
from .users import (
    UserInviteParams, UserClaimParams, UserUpdateParams, NotificationsUpdateParams,
    UserPasswordUpdateParams
)
from .auth import AuthParams, AuthResp, PasswordResetRequestParams
from .organizations import ClientParams, BusinessParams
from .reports import EmbeddedReportParams
from .grants import UserGrantUpdateParams
from .campaigns import (
    CampaignCreateParams, CampaignStatusUpdateParams, CampaignReviewParams,
    CampaignFixedBudgetAllocationParams, CampaignChannelPausedStateParams,
    CampaignArchiveStateParams, AddCampaignChannelParams, BudgetExtensionParams
)
from .ai_chats import (
    AIChatStartWSParams, AIChatMessageWSParams, AIChatMessageWSResp, AIChatStartWSResp,
    AIChatStateTransitionWSParams, AIChatSyncWSResp
)
from .locations import LocationsEmbedResp
from .assets import (
    ImageGenerationParams, ImageEditParams, AssetParams, AssetCopyParams,
    AssetSlotPoolParams, TextGenerationParams
)
from .comments import CommentCreateParams, CommentEditParams
from .ads import AdParams, AdSlotAssetParams, DisplayAdResp
from .platforms import OAuthConsentURLResp
from . import uploads, audits, analytics

from .app import app
